books/django_by_example_3/myshop/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

books/django_by_example_3/myshop/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/django_by_example_3/myshop/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("admin/order/<int:order_id>", views.admin_order_detail, name="admin_order_detail"),
    path("admin/order/<int:order_id>/pdf/", views.admin_order_pdf, name="admin_order_pdf"),
]

books/django_by_example_3/myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

books/django_by_example_3/myshop/orders/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Order(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.name} - {self.address} - {self.get_total_cost()}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.orderitem_set.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.id}"

    def get_cost(self):
        return self.price * self.quantity

books/django_by_example_3/myshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", kwargs={"category_slug": self.slug})


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d/", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", kwargs={"id": self.id, "slug": self.slug})

books/django_by_example_3/myshop/cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    PRODUCT_QUANTITY_CHOICES = (
        (i, str(i)) for i in range(1, 21)
    )

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

books/django_by_example_3/myshop/orders/forms.py
from django import forms

from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name", "email", "address"]
    

books/django_by_example_3/myshop/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from shop.models import Product

from .cart import Cart
from .forms import CartAddProductForm


# Create your views here.
@require_POST
def cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )

    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    cart = Cart(request)
    cart.remove(product)

    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(initial={
            "quantity": item["quantity"],
            "override": True
        })
    return render(request, "cart/detail.html", {"cart": cart})

books/django_by_example_3/myshop/orders/views.py
import weasyprint
from cart.cart import Cart
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string

from . import tasks
from .forms import OrderCreateForm
from .models import Order, OrderItem


# Create your views here.
def order_create(request):
    cart = Cart(request)
    form = OrderCreateForm(request.POST or None)

    if request.method == "POST":
        if not cart:
            messages.warning(request, "Your cart is empty. You cant place an order.")
            return render(
                request, "orders/order/create.html", {"cart": cart, "form": form}
            )

        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    quantity=item["quantity"],
                    price=item["price"],
                )
            cart.clear()
            
            tasks.order_created.delay(order.id)
            tasks.order_placed.delay(order.id)

            return render(request, "orders/order/created.html", {"order": order})

    return render(request, "orders/order/create.html", {"cart": cart, "form": form})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "admin/orders/order/detail.html", {"order": order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string("orders/order/pdf.html", {"order": order})
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f"filename=invoice_{order.id}.pdf"
    weasyprint.HTML(string=html).write_pdf(response)
    return response

books/django_by_example_3/myshop/shop/views.py
from cart.forms import CartAddProductForm
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


# Create your views here.
def product_list(request, category_slug=None):
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    category = None

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category__slug=category_slug)

    return render(
        request,
        "shop/product/list.html",
        {"products": products, "category": category, "categories": categories},
    )


def product_detail(request, id, slug):
    cart_add_product_form = CartAddProductForm()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(
        request,
        "shop/product/detail.html",
        {"product": product, "cart_add_product_form": cart_add_product_form},
    )

books/django_by_example_3/myshop/cart/templates/cart/detail.html
{% extends "common/base.html" %}
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}

{% block content %}
<h1>Your shopping cart</h1>

<div class="row">

    <div class="col-10">
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.image 60x60 crop=smart autocrop %}"></a>
                    </td>
                    <td>
                        {{ product.name }}
                    </td>
                    <td>
                        <form action="{% url "cart:cart_add" product.pk %}" method="POST">
                            {% csrf_token %}
                            {% bootstrap_form item.update_quantity_form show_label=False %}
                            <input type="submit" value="Update" class="btn btn-link">
                        </form>
                    </td>
                    <td>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-link" type="submit" value="Remove">
                        </form>
                    </td>
                    <td>${{ item.price }}</td>
                    <td>${{ item.total_price|floatformat:2 }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
            <tfoot>
                <tr class="table-warning">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td>${{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
            </tfoot>
        </tbody>
    </table>
    </div>

    <div class="col">
        <div class="row mb-3">
            <div class="col">
                <a href="{% url "shop:product_list" %}" class="btn btn-light w-100">Continue shopping</a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url "orders:order_create" %}" class="btn btn-success w-100">Checkout!</a>
            </div>
        </div>
    </div>

</div>
{% endblock %}

books/django_by_example_3/myshop/shop/templates/shop/product/detail.html
{% extends "common/base.html" %}

{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}

{% block content %}
<div class="card">
  <div class="card-header"><h4>{{ product.name }} <small class="text-muted"><a href="{{ product.category.get_absolute_url }}">({{ product.category.name }})</a></small></h4></div>
  <img src="{% thumbnail product.image 60x60 crop=smart autocrop %}" class="card-img-top">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}&nbsp;</p>
        <span class="badge badge-light">{{ product.price }}</span>
      </div>
      <div class="col">
        <form action="{% url "cart:cart_add" product.id %}" method="POST">
          {% csrf_token %}
          {% bootstrap_form cart_add_product_form %}
          <input class="btn btn-primary" type="submit" value="Add">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

books/django_by_example_3/myshop/shop/templates/shop/product/list.html
{% extends "common/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}

{% block content %}
<div class="row">
    <div class="col-2">
        <h4>Categories</h4>
        <ul class="list-group">
            <a href="{% url "shop:product_list" %}" class="list-group-item list-group-item-action {% if not category %}active{% endif %}">
                All
            </a>
            {% for c in categories %}
            <a href="{{ c.get_absolute_url }}" class="list-group-item {% if category.slug == c.slug %}active{% endif %}">
                {{ c.name }}
            </a>
            {% endfor %}
        </ul>
    </div>
    <div class="col-10">
        <h4>{{ category.name|title }} Products</h4>
        <div class="card-deck">
            {% for product in products %}
            <div class="card">
            <a href="{{ product.get_absolute_url }}">
                {% thumbnail product.image 60x60 crop=smart autocrop as thumb %}
                <img src="{{ thumb.url }}" class="card-img-top">
            </a>
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}&nbsp;</p>
                <span class="badge badge-light">{{ product.price }}</span>
            </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}