books/django_by_example_3/educa/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("room/<pk>/", views.CourseChatRoomView.as_view(), name="course_chat_room")
]

books/django_by_example_3/educa/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("courses/", include("courses.urls")),
    path("students/", include("students.urls")),
    path("chat/", include("chat.urls")),
    path("api/", include("courses.api.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/django_by_example_3/educa/students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from students.views import StudentCourseDetailView

from . import views

app_name = "students"
urlpatterns = [
    path(
        "register/",
        views.StudentRegistrationView.as_view(),
        name="student_registration",
    ),
    path("enroll/", views.StudentCourseEnrollView.as_view(), name="student_enroll"),
    path(
        "course/<int:pk>",
        cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
        name="student_course_detail",
    ),
    path("courses/", views.StudentCoursesView.as_view(), name="student_courses"),
]

books/django_by_example_3/educa/students/forms.py
from django import forms
from courses.models import Course

class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(Course.objects.all(), widget=forms.HiddenInput)

books/django_by_example_3/educa/students/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from . import forms
from courses import models as courses_models

# Create your views here.
class StudentRegistrationView(CreateView):
    template_name = "students/student/registration.html"
    form_class = UserCreationForm
    # success_url = reverse_lazy("students:student_course_list")
    success_url = reverse_lazy("courses:course_list")
    
    def form_valid(self, form):
        result = super().form_valid(form)

        # Register and authenticate
        cd = form.cleaned_data
        user = authenticate(username=cd["username"], password=cd["password1"])
        login(self.request, user)

        return result

class StudentCourseEnrollView(LoginRequiredMixin, FormView):
    course = None
    form_class = forms.CourseEnrollForm
    template_name = "students/student/enroll.html"

    def form_valid(self, form):
        self.course = form.cleaned_data["course"]
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("students:student_courses")

class StudentCoursesView(ListView):
    template_name = "students/student/courses.html"

    def get_queryset(self):
        return self.request.user.courses_joined.all()

class StudentCourseDetailView(DetailView):
    model = courses_models.Course
    template_name = "students/student/course_detail.html"

books/django_by_example_3/educa/students/templates/students/student/course_detail.html
{% extends "common/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h1>{{ course }}</h1>
<a href="{% url "chat:course_chat_room" course.id %}">chat</a>
{% for module in object.modules.all %}
<div class="card">
  <div class="card-header">
    {{ module }}
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
        {% for content in module.contents.all %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-1">{{ content.item.title }}</div>
                <div class="col-1">{{ content.content_type.name }}</div>
                <div class="col">
                  {{ content.item.render }}
                </div>
            </div>
        </li>
        {% empty %}
          <p>Please create some content.</p>
        {% endfor %}
    </ul>
  </div>
</div>
{% endfor %}

{% endblock %}

books/django_by_example_3/educa/students/templates/students/student/courses.html
{% extends "common/base.html" %}

{% load bootstrap4 %}

{% block content %}
<div class="card">
  <div class="card-header">
    Courses you are enrolled
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
    {% for course in object_list %}
      <a class="list-group-item" href="{% url "students:student_course_detail" course.id %}">{{ course.title }}</a>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

books/django_by_example_3/educa/students/templates/students/student/registration.html
{% extends "common/base.html" %}

{% load bootstrap4 %}

{% block content %}
<div class="card">
  <div class="card-header">
    Student Registration
  </div>
  <div class="card-body">
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons submit="Save" %}{% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}