books/django_by_example_3/bookmarks/images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("create/", views.image_create, name="create"),
    path("detail/<int:id>/<slug:slug>/", views.image_detail, name="detail"),
    path("like/", views.image_like, name="like"),
    path("list/", views.image_list, name="list"),
]

books/django_by_example_3/bookmarks/images/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name="images_created", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to="images/%Y/%m/%d/")
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    users_likes = models.ManyToManyField(
        get_user_model(), related_name="images_liked", blank=True
    )
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("images:detail", kwargs={"id": self.id, "slug": self.slug})

books/django_by_example_3/bookmarks/images/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ("title", "url", "description")
        widgets = {"url": forms.HiddenInput}

    def clean_url(self):
        url = self.cleaned_data["url"]
        valid_extensions = ["jpg", "jpeg"]
        extension = url.split(".")[-1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("We only accept jpg or jpegs")

        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)

        image_url = self.cleaned_data["url"]
        extension = image_url.split(".")[-1].lower()

        name = slugify(image.title)
        image_name = f"{name}.{extension}"

        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()

        return image

books/django_by_example_3/bookmarks/images/views.py
import redis as redislib
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from actions.utils import create_action
from common.decorators import require_AJAX

from .forms import ImageCreateForm
from .models import Image


redis = redislib.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

# Create your views here.
@login_required
def image_create(request):
    form = ImageCreateForm(data=getattr(request, request.method) or None)

    if request.method == "POST" and form.is_valid():
        form = ImageCreateForm(data=request.POST or None)
        new_item = form.save(commit=False)
        new_item.user = request.user
        new_item.save()
        messages.success(request, "Image created successfully")

        create_action(request.user, "bookmarked image", new_item)

        return redirect(new_item.get_absolute_url())

    return render(
        request, "images/image/create.html", {"section": "images", "form": form}
    )


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)

    total_views = redis.incr(f"image:{image.id}:views")
    # score
    redis.zincrby(name="image_ranking", value=image.id, amount=1)

    return render(
        request, "images/image/detail.html", {"section": "images", "image": image, "total_views": total_views}
    )


@login_required
@require_POST
@require_AJAX
def image_like(request):
    image_id = request.POST.get("id")
    image = get_object_or_404(Image, id=image_id)

    total_likes = image.users_likes.count()

    action = request.POST.get("action")
    try:
        if action == "like":
            image.users_likes.add(request.user)
            total_likes += 1
            create_action(request.user, "liked", image)
        else:
            image.users_likes.remove(request.user)
            total_likes -= 1

        return JsonResponse({"status": "ok", "total_likes": total_likes})

    except:
        return JsonResponse({"status": "error"})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 2)

    page = request.GET.get("page", 1)
    try:
        images = paginator.page(page)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        else:
            images = paginator.page(images, paginator.num_pages)

    if request.is_ajax():
        return render(
            request,
            "images/image/list_ajax.html",
            {"images": images, "section": "images"},
        )
    else:
        return render(
            request, "images/image/list.html", {"images": images, "section": "images"}
        )

books/django_by_example_3/bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

books/django_by_example_3/bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Image Detail{% endblock %}
{% block content %}
    <h1>Seeing {{ image.title }}</h1>
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    {% with total_likes=image.users_likes.count users_likes=image.users_likes.all %}
    <div class="image-info">
        <div>
            <span class="total">{{ total_likes }} like{{ total_likes|pluralize }}</span>
            <span class="count">{{ total_views}} view{{ total_views|pluralize }}</span>
        </div>
        <a class="like" href="{% url "images:like" %}" data-id="{{ image.id }}" data-action="{% if request.user in users_likes %}unlike{% else %}like{% endif %}">
            {% if request.user in users_likes %}unlike{% else %}like{% endif %}
        </a>
        <p>{{ image.description }}</p>
    </div>
    <div class="image-likes">
        {% for user in users_likes %}
        <div>
            <img src="{{ user.profile.photo.url }}" alt="">
            <p>{{ user.username }}</p>
        </div>
        {% empty %}
            <p>Nobody liked this image yet.</p>
        {% endfor %}
    </div>
    {% endwith %}
{% endblock %}

{% block domready %}
$("a.like").click(function(e){
    e.preventDefault();
    $.post(
        "{% url "images:like" %}",
        {
            id: $(this).data("id"),
            action: $(this).data("action")
        },
        function(data){
            if (data["status"] == "ok"){
                var previous_action = $("a.like").data("action");
                var new_action = previous_action == "like" ? "unlike" : "like";
                $("a.like").data("action", new_action);
                $("a.like").text(new_action);
                $("span.total").text(data["total_likes"]);
            }
        }
    );
});
{% endblock %}

books/django_by_example_3/bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Listing{% endblock %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="images-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}
{% block domready %}
var page = 1;
var empty_page = false;
var block_request = false;
$(window).scroll(function(){
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data){
            if (data == "") {
                empty_page = true;
            } else {
                block_request = false;
                $("#images-list").append(data);
            }
        })
    }
});
{% endblock %}

books/django_by_example_3/bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <img src="{{ im.url }}">
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
        </div>
    </div>
    <br>
{% endfor %}